### ISSUE TITLE
rSCAN 

### ISSUE THREAD

**Issue by bsantra** [FLOSIC/PublicRelease_2020#1]
Is this able to do rSCAN? Is there keyword for that?

**Comment by yohyamamoto** [comment]
For rSCAN, use the MGGA-RSCAN*MGGA-RSCAN keyword in SYMBOL/CLUSTER. In NRLMOL_INPUT.DAT, you will see MESHSETTINGV variable to adjust the mesh setting. Setting it to  2 gives you grid density somewhere between PBE and SCAN mesh. 

For completeness, two versions of rSCANs are included in the source code.
regscan.f (default: includes fix for PZSIC as described in the PCCP article doi:10.1039/D0CP02717K).
regscan_jcp.f (original rSCAN implementation by Bartók and Yates found in J. Chem. Phys. 150, 161101 (2019)).
