### ISSUE TITLE
 In this paper (https://doi.org/10.3390/magnetochemistry3040031) how the metal Nitrogen bonds can be understood in terms of FOD? Is there a way to reproduce the results of the paper?Welcome to PublicRelease_2020 Discussions!

### ISSUE THREAD

**Issue by suryaphy520** [FLOSIC/PublicRelease_2020#28]
### Discussed in https://github.com/FLOSIC/PublicRelease_2020/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **FLOSIC** August 28, 2021</sup>
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by yohyamamoto** [comment]
This thread should be moved to discussions.
