### ISSUE TITLE
Vibrational frequency calculation in FLOSIC code

### ISSUE THREAD

**Issue by kamal-temple** [FLOSIC/PublicRelease_2020#3]
Hi,

Can anybody help me know how one can do vibrational frequency calculation in FLOSIC code?
What input is needed and where the output is printed?

Thank you in advance!

**Comment by yohyamamoto** [comment]
For vibrational calculations, you need specsym program. 
1. Copy the following files from NRLMOL/FLOSIC: INPUT, GRPMAT, VIBINP, and SYMBOL.
2. Running specsym with "specsym VIBINP F F F 1" gives EFLDVIB, GRPVIB, SYMVIB, ISYMVIB, and mass.dat.
3. Rename GRPMAT to GRPMAT.SYM 
4. Rename GRPVIB to GRPMAT and SYMVIB to SYMBOL.
5. Run NRLMOL/FLOSIC for all the geometries in the SYMBOL. For each calculation, append FRCOUT to VIBINP e.g. 
"cat FRCOUT >> VIBINP"
6. Copy GRPMAT.SYM back to GRPMAT.
7. Run specsym with "specsym VIBINP T T T 3 > specsym.out" where the output contains vibrational modes and spectra.
